[package]
name = "lat_einv_config"
version = "0.1.0"
edition = "2021"

[lib]
name = "config"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
confy = { workspace = true }
keyring = { workspace = true }
